"""
Simple, self-contained HTML report generator for CardioScore results.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from virelion_cardioscore.analysis.pipeline import PipelineResult


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Virelion CardioScore Report</title>
  <style>
    :root {{
      --bg: #0f1419; --card: #1a2332; --text: #e7ecf3; --muted: #8b9bb4;
      --accent: #3b82f6; --low: #22c55e; --mod: #f59e0b; --high: #ef4444;
    }}
    * {{ box-sizing: border-box; }}
    body {{ font-family: system-ui, sans-serif; background: var(--bg); color: var(--text);
           margin: 0; padding: 2rem; line-height: 1.5; }}
    h1 {{ font-size: 1.75rem; margin-bottom: 0.25rem; }}
    h2 {{ font-size: 1.25rem; margin-top: 2rem; color: var(--accent); }}
    .subtitle {{ color: var(--muted); margin-bottom: 2rem; }}
    .card {{ background: var(--card); border-radius: 12px; padding: 1.25rem 1.5rem;
             margin-bottom: 1.25rem; border: 1px solid #2a3548; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 0.95rem; }}
    th, td {{ text-align: left; padding: 0.6rem 0.75rem; border-bottom: 1px solid #2a3548; }}
    th {{ color: var(--muted); font-weight: 600; }}
    .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 999px;
              font-size: 0.8rem; font-weight: 600; }}
    .badge-Low {{ background: rgba(34,197,94,0.15); color: var(--low); }}
    .badge-Moderate {{ background: rgba(245,158,11,0.15); color: var(--mod); }}
    .badge-High {{ background: rgba(239,68,68,0.15); color: var(--high); }}
    .contrib {{ display: flex; align-items: center; gap: 0.75rem; margin: 0.4rem 0; }}
    .bar {{ height: 8px; border-radius: 4px; background: var(--accent); min-width: 2px; }}
    .meta {{ font-size: 0.85rem; color: var(--muted); }}
    footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #2a3548;
              font-size: 0.8rem; color: var(--muted); }}
  </style>
</head>
<body>
  <h1>Virelion CardioScore Report</h1>
  <p class="subtitle">CiPA-aligned cardiotoxicity risk scoring · Research framework</p>
  <div class="card">
    <h2 style="margin-top:0">Summary</h2>
    <table>
      <thead><tr><th>Compound</th><th>CardioScore</th><th>Risk Class</th>
      <th>Max Conc (µM)</th><th>Wells</th></tr></thead>
      <tbody>{summary_rows}</tbody>
    </table>
  </div>
  {detail_cards}
  <div class="card">
    <h2 style="margin-top:0">Quality Control Log</h2>
    <ul class="meta">{qc_items}</ul>
  </div>
  <footer>
    Generated by Virelion CardioScore · GPL-3.0-or-later<br>
    Research and internal decision-support only. Not a validated regulatory assay.
  </footer>
</body>
</html>
"""


def write_html_report(result: "PipelineResult", path: str | Path) -> None:
    path = Path(path)
    summary_rows = []
    for _, row in result.summary_table.iterrows():
        summary_rows.append(
            f"""<tr>
              <td><strong>{row['compound']}</strong></td>
              <td>{row['cardioscore']:.3f}</td>
              <td><span class=\"badge badge-{row['risk_class']}\">{row['risk_class']}</span></td>
              <td>{row['max_concentration_uM']:.2f}</td>
              <td>{row['n_wells']}</td>
            </tr>"""
        )

    detail_cards = []
    for score in result.scores:
        contrib_html = []
        for c in score.contributions:
            width = max(2, int(c.contribution * 120))
            contrib_html.append(
                f"""<div class=\"contrib\">
                  <div style=\"width:180px;font-size:0.85rem\">{c.name}</div>
                  <div class=\"bar\" style=\"width:{width}px\"></div>
                  <span class=\"meta\">{c.contribution:.3f} (w={c.weight})</span>
                </div>"""
            )
        detail_cards.append(
            f"""<div class=\"card\">
              <h2 style=\"margin-top:0\">{score.compound}
                <span class=\"badge badge-{score.risk_class}\">{score.risk_class}</span>
              </h2>
              <p><strong>CardioScore:</strong> {score.score:.3f}</p>
              <p class=\"meta\">{score.interpretation}</p>
              <h3 style=\"font-size:1rem;margin-top:1rem\">Endpoint contributions</h3>
              {''.join(contrib_html)}
            </div>"""
        )

    qc_items = "".join(f"<li>{line}</li>" for line in result.qc_log) or "<li>No QC events recorded.</li>"

    html = HTML_TEMPLATE.format(
        summary_rows="\n".join(summary_rows),
        detail_cards="\n".join(detail_cards),
        qc_items=qc_items,
    )
    path.write_text(html, encoding="utf-8")
