"""Simple, self-contained HTML report generator for CardioScore results."""

from __future__ import annotations

from html import escape
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from virelion_cardioscore.analysis.pipeline import PipelineResult


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Virelion CardioScore Report</title>
  <style>
    :root {{
      --bg: #0f1419; --card: #1a2332; --text: #e7ecf3; --muted: #8b9bb4;
      --accent: #3b82f6; --low: #22c55e; --mod: #f59e0b; --high: #ef4444;
    }}
    * {{ box-sizing: border-box; }}
    body {{ font-family: system-ui, sans-serif; background: var(--bg); color: var(--text);
           margin: 0; padding: 2rem; line-height: 1.5; }}
    h1 {{ font-size: 1.75rem; margin-bottom: 0.25rem; }}
    h2 {{ font-size: 1.25rem; margin-top: 2rem; color: var(--accent); }}
    .subtitle {{ color: var(--muted); margin-bottom: 2rem; }}
    .card {{ background: var(--card); border-radius: 12px; padding: 1.25rem 1.5rem;
             margin-bottom: 1.25rem; border: 1px solid #2a3548; overflow-x: auto; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 0.95rem; }}
    th, td {{ text-align: left; padding: 0.6rem 0.75rem; border-bottom: 1px solid #2a3548; }}
    th {{ color: var(--muted); font-weight: 600; }}
    .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 999px;
              font-size: 0.8rem; font-weight: 600; }}
    .badge-Low {{ background: rgba(34,197,94,0.15); color: var(--low); }}
    .badge-Moderate {{ background: rgba(245,158,11,0.15); color: var(--mod); }}
    .badge-High {{ background: rgba(239,68,68,0.15); color: var(--high); }}
    .badge-stable {{ background: rgba(34,197,94,0.15); color: var(--low); }}
    .badge-high_variability {{ background: rgba(239,68,68,0.15); color: var(--high); }}
    .badge-insufficient_groups {{ background: rgba(245,158,11,0.15); color: var(--mod); }}
    .contrib {{ display: flex; align-items: center; gap: 0.75rem; margin: 0.4rem 0; }}
    .bar {{ height: 8px; border-radius: 4px; background: var(--accent); min-width: 2px; }}
    .meta {{ font-size: 0.85rem; color: var(--muted); }}
    footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #2a3548;
              font-size: 0.8rem; color: var(--muted); }}
  </style>
</head>
<body>
  <h1>Virelion CardioScore Report</h1>
  <p class="subtitle">CiPA-aligned cardiotoxicity risk scoring · Research framework</p>
  <div class="card">
    <h2 style="margin-top:0">Summary</h2>
    <table>
      <thead><tr><th>Compound</th><th>CardioScore</th><th>Risk Class</th>
      <th>Max Conc (µM)</th><th>Technical Wells</th><th>Independent Units</th></tr></thead>
      <tbody>{summary_rows}</tbody>
    </table>
  </div>
  {normalization_card}
  {variability_card}
  {detail_cards}
  <div class="card">
    <h2 style="margin-top:0">Quality Control Log</h2>
    <ul class="meta">{qc_items}</ul>
  </div>
  <footer>
    Generated by Virelion CardioScore · GPL-3.0-or-later<br>
    Research and internal decision-support only. Not a validated regulatory assay.
  </footer>
</body>
</html>
"""


def _text(value: object) -> str:
    """HTML-escape user/data-provided text before interpolation into markup."""
    return escape(str(value), quote=True)


def _format_optional_number(value: object, digits: int = 2) -> str:
    if value is None:
        return "—"
    try:
        if value != value:
            return "—"
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return _text(value)


def _build_normalization_card(result: "PipelineResult") -> str:
    diagnostic = result.normalization_diagnostic
    if not diagnostic:
        return ""

    before = result.variability_before_correction
    after = result.variability_table
    corrected = ", ".join(_text(column) for column in diagnostic.get("corrected_columns", [])) or "configured endpoints"

    rows = []
    if not before.empty and not after.empty:
        for endpoint in sorted(set(before["endpoint"]).intersection(after["endpoint"])):
            before_row = before.loc[before["endpoint"] == endpoint].iloc[0]
            after_row = after.loc[after["endpoint"] == endpoint].iloc[0]
            rows.append(
                f"""<tr>
                  <td>{_text(endpoint)}</td>
                  <td>{_format_optional_number(before_row['between_group_sd'])}</td>
                  <td>{_format_optional_number(after_row['between_group_sd'])}</td>
                  <td>{_format_optional_number(before_row['control_cv_pct'])}%</td>
                  <td>{_format_optional_number(after_row['control_cv_pct'])}%</td>
                </tr>"""
            )

    comparison = ""
    if rows:
        comparison = f"""
        <table>
          <thead><tr><th>Endpoint</th><th>Between-group SD before</th><th>After</th>
          <th>Control CV before</th><th>After</th></tr></thead>
          <tbody>{''.join(rows)}</tbody>
        </table>
        """

    return f"""<div class=\"card\">
      <h2 style=\"margin-top:0\">Control-Anchored Normalization</h2>
      <p class=\"meta\">Exploratory additive recentering learned from vehicle controls only. This does not constitute a validated batch-effect model.</p>
      <p><strong>Grouping:</strong> {_text(diagnostic.get('group_column', '—'))} &nbsp; <strong>Groups:</strong> {_format_optional_number(diagnostic.get('n_groups', '—'), 0)} &nbsp; <strong>Controls:</strong> {_format_optional_number(diagnostic.get('n_controls', '—'), 0)}</p>
      <p><strong>Corrected endpoints:</strong> {corrected}</p>
      {comparison}
    </div>"""


def _build_variability_card(result: "PipelineResult") -> str:
    if result.variability_table.empty:
        return ""

    rows = []
    for _, row in result.variability_table.iterrows():
        status = _text(row["status"])
        rows.append(
            f"""<tr>
              <td>{_text(row['endpoint'])}</td>
              <td>{_text(row['group_column'])}</td>
              <td>{int(row['n_groups'])}</td>
              <td>{int(row['n_controls'])}</td>
              <td>{_format_optional_number(row['control_cv_pct'])}%</td>
              <td>{_format_optional_number(row['between_group_sd'])}</td>
              <td><span class=\"badge badge-{status}\">{status.replace('_', ' ')}</span></td>
            </tr>"""
        )

    separation = result.separation_table
    separation_html = ""
    if not separation.empty:
        separation_rows = []
        group_column = str(separation.columns[1])
        for _, row in separation.iterrows():
            separation_rows.append(
                f"""<tr>
                  <td>{_text(row['compound'])}</td>
                  <td>{_text(row[group_column])}</td>
                  <td>{_text(row['endpoint'])}</td>
                  <td>{int(row['n_controls'])}</td>
                  <td>{int(row['n_treated'])}</td>
                  <td>{_format_optional_number(row['standardized_separation'], 3)}</td>
                </tr>"""
            )
        separation_html = f"""
        <h3 style=\"font-size:1rem;margin-top:1.25rem\">Exploratory treatment/control separation</h3>
        <table>
          <thead><tr><th>Compound</th><th>Group</th><th>Endpoint</th>
          <th>Controls</th><th>Treated</th><th>|Δ| / Control SD</th></tr></thead>
          <tbody>{''.join(separation_rows)}</tbody>
        </table>
        """

    return f"""<div class=\"card\">
      <h2 style=\"margin-top:0\">Control Stability &amp; Plate/Batch Diagnostics</h2>
      <p class=\"meta\">QC/inference diagnostics only; these values do not alter CardioScore.</p>
      <table>
        <thead><tr><th>Endpoint</th><th>Grouping</th><th>Groups</th><th>Controls</th>
        <th>Control CV</th><th>Between-group SD</th><th>Status</th></tr></thead>
        <tbody>{''.join(rows)}</tbody>
      </table>
      {separation_html}
    </div>"""


def write_html_report(result: "PipelineResult", path: str | Path) -> None:
    path = Path(path)
    summary_rows = []
    for _, row in result.summary_table.iterrows():
        risk_class = _text(row['risk_class'])
        summary_rows.append(
            f"""<tr>
              <td><strong>{_text(row['compound'])}</strong></td>
              <td>{_format_optional_number(row['cardioscore'], 3)}</td>
              <td><span class=\"badge badge-{risk_class}\">{risk_class}</span></td>
              <td>{_format_optional_number(row['max_concentration_uM'])}</td>
              <td>{int(row.get('n_technical_wells', row['n_wells']))}</td>
              <td>{int(row.get('n_independent_units', 0))}</td>
            </tr>"""
        )

    detail_cards = []
    for score in result.scores:
        risk_class = _text(score.risk_class)
        contrib_html = []
        for contribution in score.contributions:
            width = max(2, int(contribution.contribution * 120))
            contrib_html.append(
                f"""<div class=\"contrib\">
                  <div style=\"width:180px;font-size:0.85rem\">{_text(contribution.name)}</div>
                  <div class=\"bar\" style=\"width:{width}px\"></div>
                  <span class=\"meta\">{contribution.contribution:.3f} (w={contribution.weight})</span>
                </div>"""
            )
        detail_cards.append(
            f"""<div class=\"card\">
              <h2 style=\"margin-top:0\">{_text(score.compound)}
                <span class=\"badge badge-{risk_class}\">{risk_class}</span>
              </h2>
              <p><strong>CardioScore:</strong> {score.score:.3f}</p>
              <p class=\"meta\">{_text(score.interpretation)}</p>
              <p class=\"meta\">Technical wells: {score.n_wells} · Independent units: {score.n_independent_units}</p>
              <h3 style=\"font-size:1rem;margin-top:1rem\">Endpoint contributions</h3>
              {''.join(contrib_html)}
            </div>"""
        )

    qc_items = "".join(f"<li>{_text(line)}</li>" for line in result.qc_log) or "<li>No QC events recorded.</li>"

    html = HTML_TEMPLATE.format(
        summary_rows="\n".join(summary_rows),
        normalization_card=_build_normalization_card(result),
        variability_card=_build_variability_card(result),
        detail_cards="\n".join(detail_cards),
        qc_items=qc_items,
    )
    path.write_text(html, encoding="utf-8")
